# Generated by Django 3.2.9 on 2021-12-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211225_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
