# Generated by Django 3.2.9 on 2021-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='snall_description',
            field=models.TextField(max_length=500),
        ),
    ]
