# Generated by Django 3.2.9 on 2021-12-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211226_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='small_description',
            field=models.TextField(max_length=700),
        ),
    ]
