# Generated by Django 3.2.9 on 2022-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220104_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default, 1=Hidden'),
        ),
    ]
