# Generated by Django 3.2.9 on 2022-01-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_categories_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='small_description',
            field=models.TextField(max_length=1000),
        ),
    ]
